# Generated by Django 4.2.7 on 2024-06-17 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='фамилия')),
                ('name', models.CharField(blank=True, default='неизвестно', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, default='неизвестно', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='отчество')),
                ('image', models.FileField(blank=True, upload_to='personnel_gallery/', verbose_name='фото сотрудника')),
            ],
        ),
    ]
