# Generated by Django 4.2.7 on 2024-06-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePersonnel',
            new_name='ProfilePersonnelModel',
        ),
    ]
